SELECT USER AS USUARIO_CONECTADO FROM DUAL;

SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'SYSTEM'
  AND TABLE_NAME LIKE '202601%'
ORDER BY TABLE_NAME;

SELECT COUNT(*) AS CLIENTES FROM SYSTEM."202601_CLIENTE";
SELECT COUNT(*) AS PLATOS FROM SYSTEM."202601_PLATO_CARTA";
SELECT COUNT(*) AS CUENTAS FROM SYSTEM."202601_CUENTA";
SELECT COUNT(*) AS ESTADOS FROM SYSTEM."202601_ESTADO";
SELECT COUNT(*) AS REGISTROS FROM SYSTEM."202601_REGISTRO_DIARIO";
